# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  version: '$(Build.BuildNumber)'

steps:

- task: DotNetCoreInstaller@0
  inputs:
    version: '3.0.100-preview-010184'

# - script: dotnet tool install -g Cake.Tool
#   displayName: "Install Cake"

# - script: ~/.dotnet/tools/dotnet-cake -target=Pack
#   displayName: 'Build with Cake'

- script: |
    dotnet pack src/AlfrescoQuery --output $(Build.ArtifactStagingDirectory) /p:Version=$(version) /p:Configuration=Release
  displayName: "Clean and Pack"

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
